### ISSUE TITLE
validate_actions raises errors on (some) invalid actions

### ISSUE THREAD

**Issue by act65** [Lux-AI-Challenge/Lux-Design-S2#166]
I am running a 'random' agent.
```
luxai_s2 random_player/main.py random_player/main.py
```
but i am see ungraceful handling of invalid actions.

agent.py
```
from lux.kit import obs_to_game_state, GameState, EnvConfig, to_json
from lux.utils import direction_to, my_turn_to_place_factory
import numpy as np
import sys

class Agent():
    def __init__(self, player: str, env_cfg: EnvConfig) -> None:
        self.player = player
        self.opp_player = "player_1" if self.player == "player_0" else "player_0"
        self.env_cfg: EnvConfig = env_cfg

    def early_setup(self, step: int, obs, remainingOverageTime: int = 60):

        action = dict()
        if step == 0:
            # bid 0 to not waste resources bidding and declare as the default faction
            action = dict(faction="AlphaStrike", bid=0)
        else:
            game_state = obs_to_game_state(step, self.env_cfg, obs)
            # factory placement period

            # how much water and metal you have in your starting pool to give to new factories
            water_left = game_state.teams[self.player].water
            metal_left = game_state.teams[self.player].metal
            
            # how many factories you have left to place
            factories_to_place = game_state.teams[self.player].factories_to_place
            # whether it is your turn to place a factory
            my_turn_to_place = my_turn_to_place_factory(game_state.teams[self.player].place_first, step)
            if factories_to_place > 0 and my_turn_to_place:
                action = self.random_factory_spawn(obs)

        return action

    def random_factory_spawn(self, obs):
        # we will spawn our factory in a random location with 150 metal and water
        potential_spawns = np.array(list(zip(*np.where(obs["board"]["valid_spawns_mask"] == 1))))
        spawn_loc = potential_spawns[np.random.randint(0, len(potential_spawns))]
        return dict(spawn=spawn_loc, metal=150, water=150)

    def act(self, step: int, obs, remainingOverageTime: int = 60):
        actions = dict()
        state = obs_to_game_state(step, self.env_cfg, obs)

        factories = state.factories[self.player]
        units = state.units[self.player]

        for factory_id, factory in factories.items():
            a = np.random.randint(3)
            actions[factory_id] = a
    
        for unit_id, unit in units.items():
            a = [
                np.random.randint(6),
                np.random.randint(5),
                np.random.randint(5),
                np.random.standard_normal(),
                1
                ]
            actions[unit_id] = [a]

        return actions
```

and this gives

```
Traceback (most recent call last):
  File "/home/act65/miniconda3/bin/luxai_s2", line 33, in <module>
    sys.exit(load_entry_point('luxai-s2', 'console_scripts', 'luxai_s2')())
  File "/home/act65/Documents/repos/rl-games/lux/Lux-Design-S2/luxai_s2/luxai_runner/cli.py", line 96, in main
    asyncio.run(eps.run())
  File "/home/act65/miniconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/act65/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/act65/Documents/repos/rl-games/lux/Lux-Design-S2/luxai_s2/luxai_runner/episode.py", line 123, in run
    new_state_obs, rewards, dones, infos = self.env.step(actions)
  File "/home/act65/Documents/repos/rl-games/lux/Lux-Design-S2/luxai_s2/luxai_s2/env.py", line 627, in step
    actions_by_type = validate_actions(self.env_cfg, self.state, actions_by_type, verbose=self.env_cfg.verbose, weather_cfg=weather_cfg)
  File "/home/act65/Documents/repos/rl-games/lux/Lux-Design-S2/luxai_s2/luxai_s2/actions.py", line 304, in validate_actions
    water_cost = factory.water_cost(env_cfg)
  File "/home/act65/Documents/repos/rl-games/lux/Lux-Design-S2/luxai_s2/luxai_s2/factory.py", line 126, in water_cost
    return int(np.ceil(len(self.grow_lichen_positions) / config.LICHEN_WATERING_COST_FACTOR))
TypeError: object of type 'NoneType' has no len()
```

if i change the random factory actions to not allow watering (ie change to `a = np.random.randint(2)` )(which seems to be the casue of the issue above). i get more gracefully handled invalid actions. eg

```
1: [Player 0] Inappropriate action given. invalid action [[ 4.          3.          3.         -1.26433067  1.        ]] for unit_6
1: [Player 1] Inappropriate action given. invalid action [[ 1.          0.          3.         -1.13325413  1.        ]] for unit_11
0.18390464782714844
```

but i also get a new error

```
1: [Player 1] Inappropriate action given. invalid action [[ 1.          0.          2.         -1.14128725  1.        ]] for unit_9
Traceback (most recent call last):
  File "/home/act65/miniconda3/bin/luxai_s2", line 33, in <module>
    sys.exit(load_entry_point('luxai-s2', 'console_scripts', 'luxai_s2')())
  File "/home/act65/Documents/repos/rl-games/lux/Lux-Design-S2/luxai_s2/luxai_runner/cli.py", line 96, in main
    asyncio.run(eps.run())
  File "/home/act65/miniconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/act65/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/act65/Documents/repos/rl-games/lux/Lux-Design-S2/luxai_s2/luxai_runner/episode.py", line 123, in run
    new_state_obs, rewards, dones, infos = self.env.step(actions)
  File "/home/act65/Documents/repos/rl-games/lux/Lux-Design-S2/luxai_s2/luxai_s2/env.py", line 627, in step
    actions_by_type = validate_actions(self.env_cfg, self.state, actions_by_type, verbose=self.env_cfg.verbose, weather_cfg=weather_cfg)
  File "/home/act65/Documents/repos/rl-games/lux/Lux-Design-S2/luxai_s2/luxai_s2/actions.py", line 176, in validate_actions
    transfer_pos: Position = unit.pos + move_deltas[transfer_action.transfer_dir]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by act65** [comment]
ahh. when i change the `transfer_amount` to be an int it fixes the latter problem. i think. my bad...

**Comment by act65** [comment]
this issue appears to be fixed now.
