### ISSUE TITLE
Error CLI tool - numpy not installed

### ISSUE THREAD

**Issue by Tyllis** [Lux-AI-Challenge/Lux-Design-S2#189]
Running **luxai-s2 main.py main.py -v 2 -o replay.json** and got below error saying numpy is not installed, which is strange because numpy is indeed installed in the venv. 
player_1, main.py: Traceback (most recent call last):
player_1, main.py:   File "C:\Users\tyllis\Desktop\luxai_s2\main.py", line 6, in <module>
player_1, main.py:     from agent import Agent
player_1, main.py:   File "C:\Users\tyllis\Desktop\luxai_s2\agent.py", line 1, in <module>
player_1, main.py:     from lux.kit import obs_to_game_state, GameState
player_1, main.py:   File "C:\Users\tyllis\Desktop\luxai_s2\lux\kit.py", line 3, in <module>
player_1, main.py:     import numpy as np
player_1, main.py: ModuleNotFoundError: No module named 'numpy'
player_0, main.py: Traceback (most recent call last):
player_0, main.py:   File "C:\Users\tyllis\Desktop\luxai_s2\main.py", line 6, in <module>
player_0, main.py:     from agent import Agent
player_0, main.py:   File "C:\Users\tyllis\Desktop\luxai_s2\agent.py", line 1, in <module>
player_0, main.py:     from lux.kit import obs_to_game_state, GameState
player_0, main.py:   File "C:\Users\tyllis\Desktop\luxai_s2\lux\kit.py", line 3, in <module>
player_0, main.py:     import numpy as np
player_0, main.py: ModuleNotFoundError: No module named 'numpy'
player_1, main.py: cannot parse action ''
player_0, main.py: cannot parse action ''

**Comment by Tyllis** [comment]
Resolved. Issue seems to be related to venv created using Pycharm. When switching to conda env or virtualenv, the issue does not appear.
