### ISSUE TITLE
OSx Pip install luxai-s2 failing when installing vec-noise

### ISSUE THREAD

**Issue by borisalmonacid** [Lux-AI-Challenge/Lux-Design-S2#209]
OSx Pip install luxai-s2 failing when installing vec-noise
test with pip environment with pip install --upgrade luxai_s2
script.

```
Collecting vec-noise
  Downloading vec_noise-1.1.4.zip (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.1/134.1 kB 860.2 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      running dist_info
      creating /private/tmp/pip-modern-metadata-6bpf4zor/vec_noise.egg-info
      writing /private/tmp/pip-modern-metadata-6bpf4zor/vec_noise.egg-info/PKG-INFO
      writing dependency_links to /private/tmp/pip-modern-metadata-6bpf4zor/vec_noise.egg-info/dependency_links.txt
      writing requirements to /private/tmp/pip-modern-metadata-6bpf4zor/vec_noise.egg-info/requires.txt
      writing top-level names to /private/tmp/pip-modern-metadata-6bpf4zor/vec_noise.egg-info/top_level.txt
      writing manifest file '/private/tmp/pip-modern-metadata-6bpf4zor/vec_noise.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "/Users/boris/Proyectos/luxai/env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/boris/Proyectos/luxai/env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/boris/Proyectos/luxai/env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 20, in <module>
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/command/dist_info.py", line 96, in run
          self.egg_info.run()
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 312, in run
          self.find_sources()
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 320, in find_sources
          mm.run()
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 564, in run
          self.add_defaults()
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 602, in add_defaults
          sdist.add_defaults(self)
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/command/sdist.py", line 106, in add_defaults
          super().add_defaults()
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/private/tmp/pip-build-env-nrh0rajk/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "<string>", line 10, in finalize_options
      AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by StoneT2000** [comment]
are you using conda?

And can you run

```
conda list
pip list
```
and share it here.

**Comment by Exeton** [comment]
I have the same issue when using conda in wsl 2:

It looks like in https://github.com/RaRe-Technologies/gensim/issues/3225 they say "This is not needed if numpy is already installed". 

I downloaded [vec_noise](https://github.com/zbenjamin/vec_noise). I removed `__builtins__.__NUMPY_SETUP__ = False` from setup.py and tried to build  locally with pip `pip install --use-pep517 ~/luxai/vec_noise/vec_noise-master`

I was not able to build the package, so I ran `sudo apt install build-essential` and was able to build vec_noise locally.

I then ran pip install --upgrade luxai_s2

# Conda list
(luxai) root@BenPc:~/luxai# conda list
 packages in environment at /root/anaconda3/envs/luxai:

 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alsa-lib                  1.2.8                h166bdaf_0    conda-forge
attr                      2.5.1                h166bdaf_1    conda-forge
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
brotlipy                  0.7.0           py38h0a891b7_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
cairo                     1.16.0            ha61ee94_1014    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py38h4a40e3a_3    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.7            py38hfbd4bf9_0    conda-forge
cryptography              39.0.1           py38h3d167d9_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.33          py38h8dc9893_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
expat                     2.5.0                h27087fc_0    conda-forge
fftw                      3.3.10          nompi_hf0379b8_106    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0           py38h0a891b7_1    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
glib                      2.74.1               h6239696_1    conda-forge
glib-tools                2.74.1               h6239696_1    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
gst-plugins-base          1.22.0               h4243ec0_0    conda-forge
gstreamer                 1.22.0               h25f0c4b_0    conda-forge
gstreamer-orc             0.4.33               h166bdaf_0    conda-forge
gym                       0.21.0           py38he5a9106_2    conda-forge
harfbuzz                  6.0.0                h8e241bc_0    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-resources       5.12.0             pyhd8ed1ab_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
jack                      1.9.22               h11f4161_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4            py38h43d8883_1    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.14                 hfd0df8a_1    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
libbrotlidec              1.0.9                h166bdaf_8    conda-forge
libbrotlienc              1.0.9                h166bdaf_8    conda-forge
libcap                    2.66                 ha37c62d_0    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libclang                  15.0.7          default_had23c3d_1    conda-forge
libclang13                15.0.7          default_h3e3d535_1    conda-forge
libcups                   2.3.3                h36d4200_3    conda-forge
libdb                     6.2.32               h9c3ff4c_0    conda-forge
libdeflate                1.17                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libevent                  2.1.10               h28343ad_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libflac                   1.4.2                h27087fc_0    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgcrypt                 1.10.1               h166bdaf_0    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libglib                   2.74.1               h606061b_1    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libgpg-error              1.46                 h620e276_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libllvm15                 15.0.7               hadd5161_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libpq                     15.2                 hb675445_0    conda-forge
libsndfile                1.2.0                hb75c966_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libsystemd0               252                  h2a991cd_0    conda-forge
libtiff                   4.5.0                h6adf6a1_2    conda-forge
libtool                   2.4.7                h27087fc_0    conda-forge
libudev1                  253                  h0b41bf4_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.5.0                h79f4944_0    conda-forge
libxml2                   2.10.3               h7463322_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
matplotlib                3.7.0            py38h578d9bd_0    conda-forge
matplotlib-base           3.7.0            py38hd6c3c57_0    conda-forge
mpg123                    1.31.2               hcb278e6_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.32               ha901b37_0    conda-forge
mysql-libs                8.0.32               hd7da12d_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.88                 he45b914_0    conda-forge
numpy                     1.24.2           py38h10c12cc_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.0.8                h0b41bf4_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
pillow                    9.4.0            py38hde6dc18_1    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
platformdirs              3.0.0              pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
pooch                     1.7.0              pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pulseaudio                16.1                 ha8d29e2_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7           py38ha0d8c90_3    conda-forge
pyqt5-sip                 12.11.0          py38h8dc9893_3    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.8.16          he550d4f_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      3_cp38    conda-forge
qt-main                   5.15.8               h5d23da1_6    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
scipy                     1.10.1           py38h10c12cc_0    conda-forge
setuptools                67.4.0             pyhd8ed1ab_0    conda-forge
sip                       6.7.7            py38h8dc9893_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.2              py38h0a891b7_1    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
unicodedata2              15.0.0           py38h0a891b7_0    conda-forge
urllib3                   1.26.14            pyhd8ed1ab_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xcb-util                  0.4.0                h166bdaf_0    conda-forge
xcb-util-image            0.4.0                h166bdaf_0    conda-forge
xcb-util-keysyms          0.4.0                h166bdaf_0    conda-forge
xcb-util-renderutil       0.3.9                h166bdaf_0    conda-forge
xcb-util-wm               0.4.1                h166bdaf_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.8.4                h0b41bf4_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge


# Pip list

(luxai) root@BenPc:~/luxai# pip list
Package             Version
brotlipy            0.7.0
certifi             2022.12.7
cffi                1.15.1
charset-normalizer  2.1.1
cloudpickle         2.2.1
colorama            0.4.6
contourpy           1.0.7
cryptography        39.0.1
cycler              0.11.0
Cython              0.29.33
fonttools           4.38.0
gym                 0.21.0
idna                3.4
importlib-resources 5.12.0
kiwisolver          1.4.4
matplotlib          3.7.0
munkres             1.1.4
numpy               1.24.2
packaging           23.0
Pillow              9.4.0
pip                 23.0.1
platformdirs        3.0.0
ply                 3.11
pooch               1.7.0
pycparser           2.21
pyOpenSSL           23.0.0
pyparsing           3.0.9
PyQt5               5.15.7
PyQt5-sip           12.11.0
PySocks             1.7.1
python-dateutil     2.8.2
requests            2.28.2
scipy               1.10.1
setuptools          67.4.0
sip                 6.7.7
six                 1.16.0
toml                0.10.2
tornado             6.2
tqdm                4.64.1
typing_extensions   4.4.0
unicodedata2        15.0.0
urllib3             1.26.14
wheel               0.38.4
zipp                3.15.0

# Initial error
Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /root/anaconda3/envs/luxai/lib/python3.8/site-packages/setuptools/__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/vec_noise
      copying perlin.py -> build/lib.linux-x86_64-cpython-38/vec_noise
      copying shader.py -> build/lib.linux-x86_64-cpython-38/vec_noise
      copying shader_noise.py -> build/lib.linux-x86_64-cpython-38/vec_noise
      copying test.py -> build/lib.linux-x86_64-cpython-38/vec_noise
      copying __init__.py -> build/lib.linux-x86_64-cpython-38/vec_noise
      running build_ext
      building 'vec_noise._simplex' extension
      creating build/temp.linux-x86_64-cpython-38
      gcc -pthread -B /root/anaconda3/envs/luxai/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/luxai/include -fPIC -O2 -isystem /root/anaconda3/envs/luxai/include -fPIC -I/root/anaconda3/envs/luxai/include/python3.8 -I/root/anaconda3/envs/luxai/lib/python3.8/site-packages/numpy/core/include -c _simplex.c -o build/temp.linux-x86_64-cpython-38/_simplex.o -funroll-loops
      error: command 'gcc' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vec_noise
  error: subprocess-exited-with-error

  × Running setup.py install for vec_noise did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      /root/anaconda3/envs/luxai/lib/python3.8/site-packages/setuptools/__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)
      running install
      /root/anaconda3/envs/luxai/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/vec_noise
      copying perlin.py -> build/lib.linux-x86_64-cpython-38/vec_noise
      copying shader.py -> build/lib.linux-x86_64-cpython-38/vec_noise
      copying shader_noise.py -> build/lib.linux-x86_64-cpython-38/vec_noise
      copying test.py -> build/lib.linux-x86_64-cpython-38/vec_noise
      copying __init__.py -> build/lib.linux-x86_64-cpython-38/vec_noise
      running build_ext
      building 'vec_noise._simplex' extension
(base) root@BenPc:~/luxai#
      gcc -pthread -B /root/anaconda3/envs/luxai/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/luxai/include -fPIC -O2 -isystem /root/anaconda3/envs/luxai/include -fPIC -I/root/anaconda3/envs/luxai/include/python3.8 -I/root/anaconda3/envs/luxai/lib/python3.8/site-packages/numpy/core/include -c _simplex.c -o build/temp.linux-x86_64-cpython-38/_simplex.o -funroll-loops
      error: command 'gcc' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> vec_noise

note: This is an issue with the package mentioned above, not pip.

# Error when running pip install --use-pep517 vec-noise
(luxai) root@BenPc:~/luxai# pip install --use-pep517 vec-noise
Collecting vec-noise
  Using cached vec_noise-1.1.4.zip (134 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-de0sn6sn/vec_noise.egg-info
      writing /tmp/pip-modern-metadata-de0sn6sn/vec_noise.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-de0sn6sn/vec_noise.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-modern-metadata-de0sn6sn/vec_noise.egg-info/requires.txt
      writing top-level names to /tmp/pip-modern-metadata-de0sn6sn/vec_noise.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-de0sn6sn/vec_noise.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "/root/anaconda3/envs/luxai/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/anaconda3/envs/luxai/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/anaconda3/envs/luxai/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 20, in <module>
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/command/dist_info.py", line 98, in run
          self.egg_info.run()
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 318, in run
          self.find_sources()
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 326, in find_sources
          mm.run()
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 570, in run
          self.add_defaults()
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 608, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/command/sdist.py", line 106, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/tmp/pip-build-env-bqn4z86w/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "<string>", line 10, in finalize_options
      AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details

**Comment by LuisFMCuriel** [comment]
Any progress here? I'm having the same issue with a new environment set according to the official [luxai-s2](https://github.com/Lux-AI-Challenge/Lux-Design-S2) repo.

**OS: Windows**

`pip install --use-pep517 luxai-s2`

![image](https://github.com/Lux-AI-Challenge/Lux-Design-S2/assets/41307097/b6d9e4b9-a885-4c8f-897e-3ca1e8873bc7)

Error:  `'dict' object has no attribute '__NUMPY_SETUP__'`

**Comment by dmmagdal** [comment]
Throwing my hat in here to say that this does happen on my M2 as well (both `conda` and `pip`. I tried to run it on a docker container on my machine and still got the error (was hoping that the issue was OS exclusive).

**Comment by Xmaster6y** [comment]
I have a fixed fork that temporarily lives at: https://github.com/Xmaster6y/vec_noise/tree/refacto.

I can make a new pypi package if needed.
